/* Generated by tabnas-lsp-gen. */
'use strict'
const vscode = require('vscode')
const { LanguageClient } = require('vscode-languageclient/node')

let client

function activate() {
  const command = vscode.workspace.getConfiguration('tabnas')
    .get("serverPath") || "tabnas-lsp"
  client = new LanguageClient(
    "tabnas",
    "tabnas language server",
    { command, args: ['--stdio'] },
    {
      documentSelector: [
        { language: "abnf" },
        { language: "bnf" },
        { language: "pgn" },
        { language: "csv" },
        { language: "ebnf" },
        { language: "feed" },
        { language: "gbnf" },
        { language: "json5" },
        { language: "jsonic" },
        { language: "jsonl" },
        { language: "zon" },
      ],
    },
  )
  client.start()
}

function deactivate() {
  return client ? client.stop() : undefined
}

module.exports = { activate, deactivate }
