-- Generated by tabnas-lsp-gen. Neovim >= 0.11 (vim.lsp.config).
-- For older Neovim, adapt to nvim-lspconfig custom-server setup.

vim.filetype.add({ extension = {
  ["abnf"] = "abnf",
  ["bnf"] = "bnf",
  ["pgn"] = "pgn",
  ["csv"] = "csv",
  ["ebnf"] = "ebnf",
  ["rss"] = "feed",
  ["atom"] = "feed",
  ["gbnf"] = "gbnf",
  ["json5"] = "json5",
  ["jsonic"] = "jsonic",
  ["jsonl"] = "jsonl",
  ["zon"] = "zon",
} })

vim.lsp.config["tabnas_lsp"] = {
  cmd = { "tabnas-lsp", '--stdio' },
  filetypes = { "abnf", "bnf", "pgn", "csv", "ebnf", "feed", "gbnf", "json5", "jsonic", "jsonl", "zon" },
  root_markers = { '.git' },
}
vim.lsp.enable("tabnas_lsp")
