;; Generated by tabnas-lsp-gen. Eglot (built into Emacs 29+).

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode abnf-mode prog-mode "abnf")
(add-to-list 'auto-mode-alist '("\\.abnf\\'" . abnf-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(abnf-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode bnf-mode prog-mode "bnf")
(add-to-list 'auto-mode-alist '("\\.bnf\\'" . bnf-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(bnf-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode pgn-mode prog-mode "pgn")
(add-to-list 'auto-mode-alist '("\\.pgn\\'" . pgn-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(pgn-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode csv-mode prog-mode "csv")
(add-to-list 'auto-mode-alist '("\\.csv\\'" . csv-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(csv-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode ebnf-mode prog-mode "ebnf")
(add-to-list 'auto-mode-alist '("\\.ebnf\\'" . ebnf-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(ebnf-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode feed-mode prog-mode "feed")
(add-to-list 'auto-mode-alist '("\\.rss\\'" . feed-mode))
(add-to-list 'auto-mode-alist '("\\.atom\\'" . feed-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(feed-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode gbnf-mode prog-mode "gbnf")
(add-to-list 'auto-mode-alist '("\\.gbnf\\'" . gbnf-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(gbnf-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode json5-mode prog-mode "json5")
(add-to-list 'auto-mode-alist '("\\.json5\\'" . json5-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(json5-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode jsonic-mode prog-mode "jsonic")
(add-to-list 'auto-mode-alist '("\\.jsonic\\'" . jsonic-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(jsonic-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode jsonl-mode prog-mode "jsonl")
(add-to-list 'auto-mode-alist '("\\.jsonl\\'" . jsonl-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(jsonl-mode . ("tabnas-lsp" "--stdio"))))

;; A minimal major mode so eglot has something to attach to.
(define-derived-mode zon-mode prog-mode "zon")
(add-to-list 'auto-mode-alist '("\\.zon\\'" . zon-mode))
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(zon-mode . ("tabnas-lsp" "--stdio"))))
